#' Create brat htmlwidget
#' 
#' The core of the brat R package is a
#' [htmlwidget](https://www.htmlwidgets.org/) to visualise, create and modify
#' annotations of spans of text and relations of annotations. The htmlwidget
#' generated by calling the `brat()` function exposes  the functionality for the
#' JavaScript code of the [brat rapid annotation tool](https://brat.nlplab.org)
#' to R. It can be used to document annotations by embedding the widget in an R
#' Markdown document, or to interactively generate new annotations by using the
#' widget in the context of Shiny apps.
#' 
#' The input data format required by brat is a plain text representation of the
#' text to be annotated and a standoff format for annotations. The essence of this
#' standoff format is that annotated spans of text are defined by start and end
#' character offset positions.
#' 
#' The `Annotation` class defined in the
#' [NLP](https://CRAN.R-project.org/package=NLP) package is used as a flexible
#' interface between all kinds of R data formats and a brat-based annotation
#' process. The NLP package offers an established and mature binary
#' representation of a standoff format in the R context.
#' 
#' To store annotations on disk, the package uses the brat standoff format for
#' *.ann files. 'ann'-files are tab-separated definitions of annotations and
#' relations with four columns. To package includes functionality to facilitate
#' the conversion between 'ann'-files and `NLP::Annotation` objects. See the
#' documentation of these function for the specification of the ann files.
#' 
#' The core of the htmlwidget are the visualisation and annotation capabilities 
#' of the JavaScript code of the brat rapid annotation tool. The JavaScript code
#' is part of the htmlwidget, so the minimum size of the htmlwidget is the 
#' size of the JavaScript code (~ 3 GB).
#' 
#' Concerning performance, note that the brat approach to visualise annnotations
#' relies heavily on Scalable Vector Graphics (SVG). Tokens, annotations and
#' relations are SVG elements in the resulting HTML document that is part of the
#' htmlwidget. The time required for renderring the document may make itself
#' felt, when documents are long or include many annotations.
#' 
#' @seealso See the documentation of `bradget()` and `brainy()`
#' @export brat
#' @aliases brat-package brat
#' @docType package
#' @name brat
#' @import methods
#' @rdname brat
#' @author Andreas Blaette
NULL


#' @param doc_data Data to be passed into widget.
#' @param coll_data Collection data.
#' @param width The width of the widget.
#' @param height The height of the widget.
#' @param outputId The ID of the widget.
#' @rdname brat
#' @import htmlwidgets
#' @export
#' @importFrom htmlwidgets createWidget
#' @examples 
#' if (interactive()){
#'   brat(
#'     doc_data = example_doc_data,
#'     coll_data = example_coll_data
#'   )
#' }
#' 
#' # A second example
#' 
#' library(NLP)
#' merkel_min <- merkel
#' merkel_min$annotation <- merkel$annotation[merkel$annotation$type == "ner"]
#' # d <- as.BratDocData(merkel_min)
#' # collData <- list(
#' # entity_types = list(list(
#' #    type = "ner",
#' #    labels = c("Named Entity", "NE"),
#' #     bgColor = "#7fa2ff",
#' #    borderColor = "darken"
#' #   ))
#' # )
#' if (interactive()) brat(doc_data = d, coll_data = collData)
brat <- function(doc_data = list(), coll_data = list(), width = NULL, height = NULL) {
  
  x <- list(docData = doc_data, collData = coll_data)
  
  htmlwidgets::createWidget(name = "brat", x = x, width = width, height = height)
}

#' @rdname brat
#' @export
bratOutput <- function(outputId, width = "100%", height = "400px") {
  shinyWidgetOutput(outputId, "brat", width, height, package = "brat")
}

#' @param env An environment.
#' @param quoted A `logical` value.
#' @param expr An expression.
#' @rdname brat
#' @export
#' @importFrom htmlwidgets shinyRenderWidget
renderBrat <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) { expr <- substitute(expr) } # force quoted
  shinyRenderWidget(expr, bratOutput, env, quoted = TRUE)
}


#' Annotated Millenium Declaration
#' 
#' @rdname millenium_declaration 
#' @format A `AnnotatedPlainTextDocument` object as defined in the NLP package.
"millenium_declaration_annotated"

#' Annotated Speech of Angela Merkel
#' 
#' @rdname merkel
#' @format A `AnnotatedPlainTextDocument` object as defined in the NLP package.
"merkel"

#' Brat example data
#' @rdname brat_example_data
"example_doc_data"

#' Brat example data
#' @rdname brat_example_data
"example_coll_data"
